package:
  format-version: "1.0.0"
  name: "classb_pic32mzw1_wfi32e01"
  type: "application"
  status: "production"
  required: false
  version: "2.0.1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.20.0"
    - name: "core"
      type: "package"
      version: "3.14.0"
    - name: "dev_packs"
      type: "package"
      version: "3.18.1"
    - name: "bsp"
      type: "package"
      version: "3.21.1"
      
