files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 436FA3197E9DC5B765726AF9D212B505
  logicalPath: config/pic32mzw1/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 436FA3197E9DC5B765726AF9D212B505
- generatedChecksum: 4AC1450AF203C4F0B88B97282D5922A7
  logicalPath: config/pic32mzw1/classb
  name: classb.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4AC1450AF203C4F0B88B97282D5922A7
- generatedChecksum: FAC9D36E5D52F2F21C533F1F2B045A04
  logicalPath: config/pic32mzw1/classb
  name: classb_clock_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: FAC9D36E5D52F2F21C533F1F2B045A04
- generatedChecksum: F5F46AAB1B325662A21334491FA0717F
  logicalPath: config/pic32mzw1/classb
  name: classb_cpu_pc_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: F5F46AAB1B325662A21334491FA0717F
- generatedChecksum: 34B50F0F0BCC5FD3C66867CF4724B1E4
  logicalPath: config/pic32mzw1/classb
  name: classb_cpu_reg_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 34B50F0F0BCC5FD3C66867CF4724B1E4
- generatedChecksum: F511BB51F9B61C839F5288934A4F2F24
  logicalPath: config/pic32mzw1/classb
  name: classb_cpu_reg_test_asm.S
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: F511BB51F9B61C839F5288934A4F2F24
- generatedChecksum: 0B2E3F50B99927FA9487C71D8DEB43D9
  logicalPath: config/pic32mzw1/classb
  name: classb_flash_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0B2E3F50B99927FA9487C71D8DEB43D9
- generatedChecksum: F0F7B9BA10DC7ECAF5972C49229B6E23
  logicalPath: config/pic32mzw1/classb
  name: classb_interrupt_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: F0F7B9BA10DC7ECAF5972C49229B6E23
- generatedChecksum: E9DA1A1AB6A84F0FFF50504D5769813F
  logicalPath: config/pic32mzw1/classb
  name: classb_io_pin_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: E9DA1A1AB6A84F0FFF50504D5769813F
- generatedChecksum: 9D13A8D2724DB5AB95FA986F3B5E9B85
  logicalPath: config/pic32mzw1/classb
  name: classb_result_management.S
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9D13A8D2724DB5AB95FA986F3B5E9B85
- generatedChecksum: BC23CBADAB66851693A8779A01A73C2E
  logicalPath: config/pic32mzw1/classb
  name: classb_sram_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: BC23CBADAB66851693A8779A01A73C2E
- generatedChecksum: 4238740A6A08738E296E6139E26E53D8
  logicalPath: config/pic32mzw1
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4238740A6A08738E296E6139E26E53D8
- generatedChecksum: 32831A24AB668C92B80E1AC051652C83
  logicalPath: config/pic32mzw1
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 32831A24AB668C92B80E1AC051652C83
- generatedChecksum: A7A47E8DCC1A5F0E993F45D31D67C253
  logicalPath: config/pic32mzw1
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A7A47E8DCC1A5F0E993F45D31D67C253
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: F0417E15340625B1923B51DDB839F4EC
  logicalPath: config/pic32mzw1/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: F00BCC0500AECDBF9E4F9E131538B310
- generatedChecksum: F3E854D71A351784D6210C934AF24268
  logicalPath: config/pic32mzw1/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: F3E854D71A351784D6210C934AF24268
- generatedChecksum: 814F11A41C7E3327703F4283D84134EA
  logicalPath: config/pic32mzw1/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 814F11A41C7E3327703F4283D84134EA
- generatedChecksum: 302870B553042ED5294917554809F0B6
  logicalPath: config/pic32mzw1/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 302870B553042ED5294917554809F0B6
- generatedChecksum: 6299271DB22F86DA76F63ADC0269B31C
  logicalPath: config/pic32mzw1/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6299271DB22F86DA76F63ADC0269B31C
- generatedChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
  logicalPath: config/pic32mzw1/system/console
  name: sys_console.c
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
- generatedChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
  logicalPath: config/pic32mzw1/system/console
  name: sys_console_local.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
- generatedChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
  logicalPath: config/pic32mzw1/system/console
  name: sys_console_uart.c
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
- generatedChecksum: 767495C6A39617A915D8107093DC1A72
  logicalPath: config/pic32mzw1/system/console
  name: sys_console_uart.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 767495C6A39617A915D8107093DC1A72
- generatedChecksum: 5D10B9438117B64220180660AB022150
  logicalPath: config/pic32mzw1/system/console
  name: sys_console_uart_definitions.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5D10B9438117B64220180660AB022150
- generatedChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
  logicalPath: config/pic32mzw1/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
- generatedChecksum: FED2C78FCFDFAEC2E4AC890703B77760
  logicalPath: config/pic32mzw1
  name: system_pmu_mldo_trim.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: FED2C78FCFDFAEC2E4AC890703B77760
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config/pic32mzw1
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config/pic32mzw1/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: D4C6E928D289C9C949F1D14FE0887451
  logicalPath: config/pic32mzw1/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: D4C6E928D289C9C949F1D14FE0887451
- generatedChecksum: 9BCFFD379813352A1B1578266DF28B45
  logicalPath: config/pic32mzw1/classb
  name: classb.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 9BCFFD379813352A1B1578266DF28B45
- generatedChecksum: 4610410CCB83BB916036504DF58CA285
  logicalPath: config/pic32mzw1/classb
  name: classb_clock_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 4610410CCB83BB916036504DF58CA285
- generatedChecksum: 75E66AB201A469248F36F0ADA0DB8F6D
  logicalPath: config/pic32mzw1/classb
  name: classb_common.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 75E66AB201A469248F36F0ADA0DB8F6D
- generatedChecksum: 766FA7D73F5BDDB5C5A3A662E1E60E34
  logicalPath: config/pic32mzw1/classb
  name: classb_cpu_reg_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 766FA7D73F5BDDB5C5A3A662E1E60E34
- generatedChecksum: 9194BF4328BD9DCA3F40C81121E50396
  logicalPath: config/pic32mzw1/classb
  name: classb_flash_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 9194BF4328BD9DCA3F40C81121E50396
- generatedChecksum: 1EA58D99878D53B0E229FC742A096B30
  logicalPath: config/pic32mzw1/classb
  name: classb_interrupt_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 1EA58D99878D53B0E229FC742A096B30
- generatedChecksum: 131CC8306DA97AD53A51B1BC47A20B53
  logicalPath: config/pic32mzw1/classb
  name: classb_io_pin_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 131CC8306DA97AD53A51B1BC47A20B53
- generatedChecksum: F60FDA6A09523F64469D50B901D8BCBE
  logicalPath: config/pic32mzw1/classb
  name: classb_sram_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: F60FDA6A09523F64469D50B901D8BCBE
- generatedChecksum: 043CCE68FD781855F0C15288BBD5A182
  logicalPath: config/pic32mzw1
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 043CCE68FD781855F0C15288BBD5A182
- generatedChecksum: 34934259CEEC6BC63A269DEF6270653E
  logicalPath: config/pic32mzw1
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 34934259CEEC6BC63A269DEF6270653E
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config/pic32mzw1
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mzw1/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mzw1/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mzw1/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mzw1/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B358678B02AC7D3AD6CC80621ECC826D
  logicalPath: config/pic32mzw1/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B358678B02AC7D3AD6CC80621ECC826D
- generatedChecksum: 9238A3759A2C6748FE493370DE35B5E0
  logicalPath: config/pic32mzw1/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 9238A3759A2C6748FE493370DE35B5E0
- generatedChecksum: 7F65C8062DF1367D5D6B401389DA270A
  logicalPath: config/pic32mzw1/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F65C8062DF1367D5D6B401389DA270A
- generatedChecksum: 3C52CEA231878411E3950ADD556AF20C
  logicalPath: config/pic32mzw1/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C52CEA231878411E3950ADD556AF20C
- generatedChecksum: FBB2DEFAADE0488ACAFA5C5FB807B149
  logicalPath: config/pic32mzw1/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: FBB2DEFAADE0488ACAFA5C5FB807B149
- generatedChecksum: D5B124F7B292B92BE6CA0A7BDFD6F62F
  logicalPath: config/pic32mzw1/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: D5B124F7B292B92BE6CA0A7BDFD6F62F
- generatedChecksum: CB4B34D1ABCE74BF62A89A7FF936BE91
  logicalPath: config/pic32mzw1/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: CB4B34D1ABCE74BF62A89A7FF936BE91
- generatedChecksum: 91CB36F6EC29DAA7C584282A875E5CBA
  logicalPath: config/pic32mzw1/system/console
  name: sys_console.h
  physicalPath: system/console
  security: NON_SECURE
  type: HEADER
  userChecksum: 91CB36F6EC29DAA7C584282A875E5CBA
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mzw1/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mzw1/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mzw1/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mzw1/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mzw1/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mzw1/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mzw1
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config/pic32mzw1
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 34C817709D3F54FE0AD5A90F33B4CB7C
  logicalPath: config/pic32mzw1
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 34C817709D3F54FE0AD5A90F33B4CB7C
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mzw1;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;
  key: oXC32ld-extra-opts
  security: NON_SECURE
  value: -mreserve=data@0x00000000:0x00000400
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mzw1;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
