files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 436FA3197E9DC5B765726AF9D212B505
  logicalPath: config/pic32mzw1/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 436FA3197E9DC5B765726AF9D212B505
- generatedChecksum: E4971CAD4BB18948D85E76B50134A87E
  logicalPath: config/pic32mzw1/classb
  name: classb.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: E4971CAD4BB18948D85E76B50134A87E
- generatedChecksum: DE507BA55207C80045A717A0AB2F783C
  logicalPath: config/pic32mzw1/classb
  name: classb_clock_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE507BA55207C80045A717A0AB2F783C
- generatedChecksum: 836A2451B32C97EC0C809709F74FD3C7
  logicalPath: config/pic32mzw1/classb
  name: classb_cpu_pc_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 836A2451B32C97EC0C809709F74FD3C7
- generatedChecksum: D311BE5D25BAF7452AC5F04C78C5D9A5
  logicalPath: config/pic32mzw1/classb
  name: classb_cpu_reg_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: D311BE5D25BAF7452AC5F04C78C5D9A5
- generatedChecksum: 1967E67C0802AE052D0FDDDF6F118B23
  logicalPath: config/pic32mzw1/classb
  name: classb_cpu_reg_test_asm.S
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1967E67C0802AE052D0FDDDF6F118B23
- generatedChecksum: 1FBE94F33639A6DA6A9C73992492DE91
  logicalPath: config/pic32mzw1/classb
  name: classb_flash_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1FBE94F33639A6DA6A9C73992492DE91
- generatedChecksum: E328C8C0482537C6C4B075F937287E08
  logicalPath: config/pic32mzw1/classb
  name: classb_interrupt_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: E328C8C0482537C6C4B075F937287E08
- generatedChecksum: 7E3767B48378CF7CA3DF2255C53189B0
  logicalPath: config/pic32mzw1/classb
  name: classb_io_pin_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7E3767B48378CF7CA3DF2255C53189B0
- generatedChecksum: 1F8A69850462C7AD43D2F579A788381E
  logicalPath: config/pic32mzw1/classb
  name: classb_result_management.S
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F8A69850462C7AD43D2F579A788381E
- generatedChecksum: BA4325C0333458B577296FD7554D97A7
  logicalPath: config/pic32mzw1/classb
  name: classb_sram_algorithm.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: BA4325C0333458B577296FD7554D97A7
- generatedChecksum: A1F03F215EFA271AA438D428DB6FDC8A
  logicalPath: config/pic32mzw1/classb
  name: classb_sram_test.c
  physicalPath: classb
  security: NON_SECURE
  type: SOURCE
  userChecksum: A1F03F215EFA271AA438D428DB6FDC8A
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mzw1
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: BDAC96EC291040C7AC410D484CF02943
  logicalPath: config/pic32mzw1
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BDAC96EC291040C7AC410D484CF02943
- generatedChecksum: 84A1EEA53FC5216B91EA7FABEAB431FA
  logicalPath: config/pic32mzw1
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 84A1EEA53FC5216B91EA7FABEAB431FA
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: B19B292DD0D4A6475C6BBEFD37531177
  logicalPath: config/pic32mzw1/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: B19B292DD0D4A6475C6BBEFD37531177
- generatedChecksum: D1E3BBAFAE83571C644CD56C2747168C
  logicalPath: config/pic32mzw1/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: D1E3BBAFAE83571C644CD56C2747168C
- generatedChecksum: 98AB2CEE4F371667A7FC6D08AD7BC186
  logicalPath: config/pic32mzw1/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 98AB2CEE4F371667A7FC6D08AD7BC186
- generatedChecksum: 302870B553042ED5294917554809F0B6
  logicalPath: config/pic32mzw1/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 302870B553042ED5294917554809F0B6
- generatedChecksum: 58E19204ED8AD966B1A5D564BCF5DA6C
  logicalPath: config/pic32mzw1/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 58E19204ED8AD966B1A5D564BCF5DA6C
- generatedChecksum: 290251D6FF0845DC4259E0EF74DCB657
  logicalPath: config/pic32mzw1
  name: pmu_init.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 290251D6FF0845DC4259E0EF74DCB657
- generatedChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
  logicalPath: config/pic32mzw1/system/console
  name: sys_console.c
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
- generatedChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
  logicalPath: config/pic32mzw1/system/console
  name: sys_console_local.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
- generatedChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
  logicalPath: config/pic32mzw1/system/console
  name: sys_console_uart.c
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
- generatedChecksum: 767495C6A39617A915D8107093DC1A72
  logicalPath: config/pic32mzw1/system/console
  name: sys_console_uart.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 767495C6A39617A915D8107093DC1A72
- generatedChecksum: 5D10B9438117B64220180660AB022150
  logicalPath: config/pic32mzw1/system/console
  name: sys_console_uart_definitions.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5D10B9438117B64220180660AB022150
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mzw1/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config/pic32mzw1
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mzw1/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: D4C6E928D289C9C949F1D14FE0887451
  logicalPath: config/pic32mzw1/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: D4C6E928D289C9C949F1D14FE0887451
- generatedChecksum: 7CF6FE24CF3CBC4462695CA649236EF1
  logicalPath: config/pic32mzw1/classb
  name: classb.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 7CF6FE24CF3CBC4462695CA649236EF1
- generatedChecksum: FD186920EC22392493420F156CD3CFFF
  logicalPath: config/pic32mzw1/classb
  name: classb_clock_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: FD186920EC22392493420F156CD3CFFF
- generatedChecksum: E4535D945010B99249B2FECFD38171D8
  logicalPath: config/pic32mzw1/classb
  name: classb_common.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: E4535D945010B99249B2FECFD38171D8
- generatedChecksum: 6F4639187BA6D98FBDFB75263255EAE0
  logicalPath: config/pic32mzw1/classb
  name: classb_cpu_reg_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 6F4639187BA6D98FBDFB75263255EAE0
- generatedChecksum: 58DE6EFB75B43AFCFC2FAB93647E01EC
  logicalPath: config/pic32mzw1/classb
  name: classb_flash_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 58DE6EFB75B43AFCFC2FAB93647E01EC
- generatedChecksum: E9E98982AD2444E46530C1DD7E46EE62
  logicalPath: config/pic32mzw1/classb
  name: classb_interrupt_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: E9E98982AD2444E46530C1DD7E46EE62
- generatedChecksum: DE538BC5BF87C656B41229ACD7D4B14A
  logicalPath: config/pic32mzw1/classb
  name: classb_io_pin_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: DE538BC5BF87C656B41229ACD7D4B14A
- generatedChecksum: A9800031070AB34129C6F86FE270C807
  logicalPath: config/pic32mzw1/classb
  name: classb_result_management.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: A9800031070AB34129C6F86FE270C807
- generatedChecksum: D8EABEB4BD6A88FC392977082F1DAEFF
  logicalPath: config/pic32mzw1/classb
  name: classb_sram_algorithm.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: D8EABEB4BD6A88FC392977082F1DAEFF
- generatedChecksum: 7F7C05B6DE85E2369B127CA25A17D7FF
  logicalPath: config/pic32mzw1/classb
  name: classb_sram_test.h
  physicalPath: classb
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F7C05B6DE85E2369B127CA25A17D7FF
- generatedChecksum: 8AA8A1E83CBC193636026F2669081F9D
  logicalPath: config/pic32mzw1
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 8AA8A1E83CBC193636026F2669081F9D
- generatedChecksum: DF64D7F87BC6A0F1985E989A2BDDF919
  logicalPath: config/pic32mzw1
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: DF64D7F87BC6A0F1985E989A2BDDF919
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mzw1
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mzw1/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mzw1/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mzw1
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mzw1/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mzw1/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mzw1/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: F4C7B8A950B1D12FF6EC959D0A996B5B
  logicalPath: config/pic32mzw1/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: F4C7B8A950B1D12FF6EC959D0A996B5B
- generatedChecksum: 2B5072810107E051495C4B6379DEDA4E
  logicalPath: config/pic32mzw1/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B5072810107E051495C4B6379DEDA4E
- generatedChecksum: BFA90471A89ED563A27D8E3D12373D5E
  logicalPath: config/pic32mzw1/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: BFA90471A89ED563A27D8E3D12373D5E
- generatedChecksum: FBB2DEFAADE0488ACAFA5C5FB807B149
  logicalPath: config/pic32mzw1/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: FBB2DEFAADE0488ACAFA5C5FB807B149
- generatedChecksum: D5B124F7B292B92BE6CA0A7BDFD6F62F
  logicalPath: config/pic32mzw1/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: D5B124F7B292B92BE6CA0A7BDFD6F62F
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mzw1/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 91CB36F6EC29DAA7C584282A875E5CBA
  logicalPath: config/pic32mzw1/system/console
  name: sys_console.h
  physicalPath: system/console
  security: NON_SECURE
  type: HEADER
  userChecksum: 91CB36F6EC29DAA7C584282A875E5CBA
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mzw1/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mzw1/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mzw1/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mzw1/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mzw1/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mzw1/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mzw1
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: null
  logicalPath: config/pic32mzw1
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: C24B1DDDFF40F7DDFC8B469DD39FDEDE
  logicalPath: config/pic32mzw1
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C24B1DDDFF40F7DDFC8B469DD39FDEDE
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mzw1;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;
  key: oXC32ld-extra-opts
  security: NON_SECURE
  value: -mreserve=data@0x00000000:0x000003ff
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mzw1;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
